name: Ollama Diagnostic Smoke Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  ollama-diag:
    name: Ollama diagnostic
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Keep Node setup available if later diagnostic scripts need node tooling
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Local script (if present)
        id: local_script
        run: |
          echo "Looking for scripts/ollama-diag.sh ..."
          if [ -x scripts/ollama-diag.sh ]; then
            echo "Found; executing (non-blocking)."
            scripts/ollama-diag.sh || echo "Local diag script exited with non-zero (ignored)"
          else
            echo "No local script found; skipping."
          fi
        continue-on-error: true

      - name: Basic reachability check
        id: reachability
        run: |
          set -e
          OLLAMA_HOST="${{ secrets.OLLAMA_HOST }}"
          if [ -z "$OLLAMA_HOST" ]; then
            OLLAMA_HOST="http://127.0.0.1:11434"
          fi
          echo "Target Ollama host: $OLLAMA_HOST"
          if curl --silent --fail --max-time 5 "$OLLAMA_HOST/health" >/dev/null 2>&1; then
            echo "Health endpoint reachable."
          else
            echo "Health endpoint NOT reachable (non-blocking)."
            exit 0
          fi
          if curl --silent --fail --max-time 5 "$OLLAMA_HOST/v1/models" >/dev/null 2>&1; then
            echo "Models endpoint reachable."
          else
            echo "Models endpoint NOT reachable (non-blocking)."
          fi
        continue-on-error: true

      - name: Optional repo diag endpoint
        run: |
          if command -v curl >/dev/null 2>&1; then
            if curl --silent --fail --max-time 5 "http://127.0.0.1:8000/diag/ollama" >/dev/null 2>&1; then
              echo "Repo diag endpoint reachable."
            else
              echo "Repo diag endpoint not reachable (ok)."
            fi
          fi
        continue-on-error: true
