name: Refactor Split Smoke

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  split-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run splitter (non-interactive)
        shell: pwsh
        run: |
          ./scripts/split-and-manifest.ps1 `
            -Source 'contracts/dispacher/ManifestDispacher.sol' `
            -OutDir 'artifacts/splits' `
            -CiMode `
            -FailOnEmptyParts

      - name: Sanity checks
        run: |
          node -e "const c=require('./artifacts/splits/combined.json'); if(!c.parts||!c.selectors){throw new Error('Empty split manifest: '+JSON.stringify(c))}"
          node scripts/validate-split.js

      - name: ABI Parity Check
        run: npm run check:abi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: split-manifest-ubuntu
          path: artifacts/splits

  split-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run splitter (Windows)
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -File scripts\split-and-manifest.ps1 `
            -Source contracts\dispacher\ManifestDispacher.sol `
            -OutDir artifacts\splits `
            -CiMode `
            -FailOnEmptyParts

      - name: Sanity checks
        shell: bash
        run: |
          node -e "const c=require('./artifacts/splits/combined.json'); if(!c.parts||!c.selectors){throw new Error('Empty split manifest: '+JSON.stringify(c))}"
          node scripts/validate-split.js

      - name: ABI Parity Check
        run: npm run check:abi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: split-manifest-windows
          path: artifacts/splits
