name: Refactor Split Smoke

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  split-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Run splitter (non-interactive)
        # Run pwsh from bash to avoid multi-line pwsh wrapper/argument parsing issues on ubuntu runners
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File scripts/split-and-manifest.ps1 -Source 'contracts/dispacher/ManifestDispacher.sol' -OutDir 'artifacts/splits' -CiMode -FailOnEmptyParts

      - name: Sanity checks
        run: |
          node -e "const c=require('./artifacts/splits/combined.json'); if(!c.parts||!c.selectors){throw new Error('Empty split manifest: '+JSON.stringify(c))}"
          node scripts/validate-split.js

      - name: ABI subset parity
        run: node scripts/validate-manifest-selectors.js --mode=subset --source contracts/dispacher/ManifestDispacher.sol --combined artifacts/splits/combined.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: split-manifest-ubuntu
          path: artifacts/splits

      - name: ABI exact parity (strict, release only)
        if: startsWith(github.ref, 'refs/tags/')
        run: node scripts/validate-manifest-selectors.js --mode=strict --source contracts/dispacher/ManifestDispacher.sol --combined artifacts/splits/combined.json

  split-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Run splitter (Windows)
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -File scripts\split-and-manifest.ps1 `
            -Source contracts\dispacher\ManifestDispacher.sol `
            -OutDir artifacts\splits `
            -CiMode `
            -FailOnEmptyParts

      - name: Sanity checks
        shell: bash
        run: |
          node -e "const c=require('./artifacts/splits/combined.json'); if(!c.parts||!c.selectors){throw new Error('Empty split manifest: '+JSON.stringify(c))}"
          node scripts/validate-split.js

      - name: ABI subset parity
        shell: pwsh
        run: |
          node scripts/validate-manifest-selectors.js --mode=subset --source contracts\dispacher\ManifestDispacher.sol --combined artifacts\splits\combined.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: split-manifest-windows
          path: artifacts/splits

      - name: ABI exact parity (strict, release only)
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        run: |
          node scripts/validate-manifest-selectors.js --mode=strict --source contracts\dispacher\ManifestDispacher.sol --combined artifacts\splits\combined.json
